# EXPLORATORY DATA ANALYSIS 


# ADMISSIONS BY YEAR 
SELECT YEAR(`DATE OF ADMISSION`)`YEAR`, COUNT(`NAME`) NUMBER_OF_ADMISSION
FROM healthcare_dataset_staging2
GROUP BY `YEAR`
ORDER BY `YEAR`; ;

# NUMBER OF PATIENTS ADMITTED GROUPED BY AGE GROUP( CHILD, ADULTS, SENIORS)
SELECT
CASE 
	WHEN AGE < 18 THEN  'CHILD'
	WHEN AGE BETWEEN 18 AND 64 THEN 'ADULTS' 
	WHEN AGE>64 THEN 'SENIOR'
END  AS AGE_GROUP, COUNT(*) AS NUMBERS_OF_PATIENT_ADMITTED
FROM HEALTHCARE_DATASET
GROUP BY AGE_GROUP 
ORDER BY NUMBERS_OF_PATIENT_ADMITTED DESC ;

# MOST COMMON MEDICAL CONDITION ORDERED IN DESC ORDER 
SELECT `MEDICAL CONDITION`, COUNT(`MEDICAL CONDITION`) NUMBERS_OF_PATIENT
FROM healthcare_dataset_staging2
GROUP BY `MEDICAL CONDITION`
ORDER BY NUMBERS_OF_PATIENT DESC;


# NUMBER OF DAYS PATIENTS ARE ADMITTED IN HOSPITAL BASED ON MEDICAL CONDITION
SELECT `MEDICAL CONDITION`, COUNT(`MEDICAL CONDITION`) NUMBERS_OF_PATIENT ,ROUND(AVG( datediff( `DISCHARGE DATE`,`DATE OF ADMISSION`)),2) AVG_NUMOF_DAYS_IN_HOSPITAL FROM healthcare_dataset_staging2
GROUP BY `MEDICAL CONDITION`
ORDER BY AVG_NUMOF_DAYS_IN_HOSPITAL DESC ;
# PATIENT UNDER AGE 18 HAS MOST NUMBER OF MEDICAL CONDITION WITH OBESITY AND LEAST NUMBER OF HYPERTENSION 
# ABOVE QUERY TELLS THE AVERAGE NUMBER OF DAYS PATIENT WERE ADMITTED ACCORDING TO AGE AND MEDICAL CONDITION


# Prevelance of Medical coditions(disease) among particular age group
SELECT `MEDICAL CONDITION`, COUNT(`MEDICAL CONDITION`)NUM_OF_CHILD_PATIENT
FROM healthcare_dataset_staging2
WHERE AGE < 18 
GROUP BY `MEDICAL CONDITION` 
ORDER BY NUM_OF_CHILD_PATIENT DESC;

# ROLLING TOTAL OF BILLING AMOUNT BY MONTH
WITH CTE AS (SELECT substring(`DATE OF ADMISSION`,1,7) AS `MONTH` , ROUND(SUM(`BILLING AMOUNT`)/1000000,2) AS MONTHLY_TOTAL_BILL_IN_MILLION FROM healthcare_dataset_staging2
GROUP BY `MONTH`
ORDER BY `MONTH`)
SELECT `MONTH`,MONTHLY_TOTAL_BILL_IN_MILLION, ROUND(SUM(MONTHLY_TOTAL_BILL_IN_MILLION) OVER (ORDER BY `MONTH`),2) AS ROLLING_TOTAL_BYMONTH 
FROM CTE;

# TOP INSURANCE PROVIDER WITH HIGHEST TOTAL BILLING AMOUNT FOR EACH YEAR
WITH CTE AS (SELECT `INSURANCE PROVIDER`, COUNT(`INSURANCE PROVIDER`) NUMBER_OF_PATIENT, ROUND(SUM(`Billing Amount`/1000000),2) AS TOTAL_BILL_In_MILLION 
FROM healthcare_dataset_staging2
GROUP BY `INSURANCE PROVIDER`)
SELECT *, ROUND(sum(TOTAL_BILLinMILLION) OVER(ORDER BY `INSURANCE PROVIDER`),2) AS ROLLING_TOTAL_IN_MILLION FROM CTE;
;

WITH CTE AS (SELECT `INSURANCE PROVIDER`, YEAR(`DATE OF ADMISSION`)`YEAR`, ROUND(SUM(`BILLING AMOUNT`/1000000),2) TOTALBILL_IN_MILLION
FROM healthcare_dataset_staging2
GROUP BY `Insurance Provider`, YEAR(`DATE OF ADMISSION`)
ORDER BY `INSURANCE PROVIDER`),
INSURANCE_YEAR_RANK AS (SELECT *, dense_rank() OVER (partition by  `YEAR` ORDER BY TOTALBILL_IN_MILLION) RANKING FROM CTE)
SELECT * FROM INSURANCE_YEAR_RANK WHERE RANKING = 1;

SELECT * FROM healthcare_dataset_staging2;



